[build]
  # No build command needed - just functions
  command = "echo 'No build required for backend functions'"
  
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# CORS settings for contact form
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"